### ISSUE TITLE
focus-visible problem

### ISSUE THREAD

**Issue by danbord** [uktrade/cypress-image-diff#103]
The CSS **:focus-visible** state style on a button is sometimes applied and sometimes not when calling **compareSnapshot**.  Which makes my test fail.

I tried with the cy.screenshot and seems to be always applied.  Not sure what could cause this difference between

**Comment by nmkataoka** [comment]
@danbord Could you provide a reproducible example?

**Comment by JasonFairchild** [comment]
Could this be based on whether the window running the test is in focus or not? This should only apply when running the test in cypress open mode, and I think it is an unavoidable aspect of cypress/browsers. Happens to me all the time. We made a custom assertion/message testing focus to put just before the compareSnapshot command so that is is clearer what the problem is.
