### ISSUE TITLE
'scroll-behavior: smooth' causes issues with full page screenshots

### ISSUE THREAD

**Issue by Edwardmunn** [uktrade/cypress-image-diff#146]
One site I have recently been testing uses the following CSS property: `html { scroll-behavior: auto; }`. This causes the page to smoothly scroll to an anchor, or the top of the page. However, when a full page screenshot is being captured, the page is still smoothly scrolling up, causing issues.

The screenshot captured repeatedly shows that is displayed at the viewport height.

I have solved this on my particular project buy using the following: `cy.get('html').invoke('css', 'scroll-behavior', 'auto')`. However, this may not work for all sites.

The plugin should probably do one of the following:
* Ensure that the page is not scrolling when a full page screenshot is being captured
* Find a way to jump to the top of the page instantly 

Thanks team,
Edward.

**Comment by kien-ht** [comment]
Hi. This issue is more related to `Cypress` itself and how `cypress.screenshot` command takes screenshots. Like you said, whatever we are trying to do here is just a hacky workaround, and we don't feel comfortable proceeding with implementing this particular feature.
However, we will update our docs to give other people a heads up about this issue. Thank you for your suggestion. 🙌
