### ISSUE TITLE
Cannot read properties of undefined (reading 'FAIL_ON_MISSING_BASELINE')

### ISSUE THREAD

**Issue by SaulGoode77** [uktrade/cypress-image-diff#172]
It seems I get this error if I don't use the cypress-image-diff.config.js file with the config FAIL_ON_MISSING_BASELINE set in there.  Anyway around this?  

![Screenshot 2023-09-09 at 12 01 39 PM](https://github.com/uktrade/cypress-image-diff/assets/82179239/071c575f-a1dd-4f41-be23-96c5c5d2afe6)

**Comment by kien-ht** [comment]
Hi. You should be fine without a config file if you don't need it. Could you share your plugin setup and configuration please?

**Comment by SaulGoode77** [comment]
cypress.config.ts
`e2e: {
    supportFile: 'cypress/support/e2e.ts',
    testIsolation: false,
    setupNodeEvents(on, config) {
      require('cypress-image-diff-js/dist/plugin')(on, config);
      getCompareSnapshotsPlugin(on, config);
      // @ts-ignore
      on('before:browser:launch', (browser = {}, launchOptions) => {
        // @ts-ignore
        if (browser.family === 'chromium') {
          launchOptions.args.push('--force-dark-mode=true');
          launchOptions.args.push('--window-size=1920,2160');
          return launchOptions;
        }
      });
    }
  }
`
e2e.ts
`const compareSnapshotCommand = require('cypress-image-diff-js/dist/command');
compareSnapshotCommand();`

if I change `getCompareSnapshotsPlugin(on, config);` to `return getCompareSnapshotsPlugin(on, config);` which seems to stop the error from occurring, then the `before:browser:launch` section won't work and I need that part to test dark-mode.

**Comment by kien-ht** [comment]
Yes. That's right. You need to return `getCompareSnapshotsPlugin(on, config)` in the function body of `setupNodeEvents`, as [our docs mention](https://github.com/uktrade/cypress-image-diff#custom-config-file).

`before:browser:launch` won't work on your side because we have already internally used this event. If we register the same event more than once, `Cypress` will only apply the handler of the last one. This is a `Cypress` limitation, [see this issue](https://github.com/cypress-io/cypress/issues/5240).

To overcome this, you could wrap the `on` function before passing it to our plugin and forward all events.

**Comment by SaulGoode77** [comment]
But I thought that using the cypress-image-diff.config.js file was optional?

**Comment by kien-ht** [comment]
`cypress-image-diff.config.js` file is indeed optional. I just created a pull request for the case where you don't want to return `getCompareSnapshotsPlugin` and want the default config.

**Comment by SaulGoode77** [comment]
> `cypress-image-diff.config.js` file is indeed optional. I just created a pull request for the case where you don't want to return `getCompareSnapshotsPlugin` and want the default config.

That's amazing!  Thank you so much!  
Really love this plugin, it's the best one out there I find.
